# Generated by Django 4.1 on 2022-11-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_country', models.CharField(max_length=100)),
                ('origin', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('services', models.CharField(choices=[('1', 'Standard'), ('2', 'Premium')], max_length=200)),
                ('date', models.DateField(null=True, unique=True)),
                ('select', models.CharField(choices=[('1', 'Self'), ('2', 'Other')], max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('1', 'Standard'), ('2', 'Premium')], max_length=200)),
                ('date', models.DateField(null=True, unique=True)),
                ('select', models.CharField(choices=[('1', 'Self'), ('2', 'Other')], max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
