# Generated by Django 4.1 on 2022-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=200)),
                ('date', models.DateField(null=True, unique=True)),
                ('select', models.CharField(choices=[('self', 'Self'), ('other', 'Other')], max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='domestic',
            name='destination',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='origin',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='international',
            name='destination',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='international',
            name='origin',
            field=models.IntegerField(max_length=6),
        ),
    ]
