# Generated by Django 4.1 on 2022-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_details_parcel_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='select',
        ),
        migrations.AddField(
            model_name='details',
            name='from_whom',
            field=models.CharField(choices=[('1', 'Self'), ('2', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
