# Generated by Django 4.1 on 2022-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_details_select_details_from_whom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
