# Generated by Django 4.1 on 2022-11-22 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestic',
            name='destination',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='origin',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
